Fixed doxygen (missing enum docs), now fail on undocumented

diff --git a/.github/workflows/nightly-build.yml b/.github/workflows/nightly-build.yml
--- a/.github/workflows/nightly-build.yml
+++ b/.github/workflows/nightly-build.yml
@@ -250,7 +250,8 @@ jobs:
     - name: Build documentation
       if: env.REBUILD == 'true'
       run: |
-        make docs doxygen
+        make docs
+        make doxygen || true # don't fail on undocumented features here
         rm -f bin/doc/*.bigpdf
         cp doc/presentations/*.pdf bin/doc || true
         echo "${{ env.VERSION }}" >bin/doxy/docversion.txt
